config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "products/manage_products", as: "manage_products"
  get "products/search", as: "search"
  get "products/sort", as: "sort"

  resources :categories
  resources :products
  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :stock, dependent: :destroy,inverse_of: :product 
    has_one :category, through: :stock
    validates :price, presence: true
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    mount_uploader :image, ImageUploader

    accepts_nested_attributes_for :stock, reject_if: :all_blank, allow_destroy: true
    default_scope { order(:name) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @categories = Category.all
        @products = Product.all
        @product = Product.first
    end

    def new
        @categories = Category.all
        @product = Product.new
    end

    def create
     @product= Product.new(product_params)
     if @product.save
        flash[:notice] ="Created Succesfully"
     else
        flash[:alert] = @product.errors.full_messages
     end
     redirect_to action: "new"
    end

    def update
        @product = Product.find_by_id(params[:id])
        if @product.update_attributes(product_params)
            redirect_to manage_products_path
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find_by_id(params[:id])
        if @product.destroy
            flash[:success] = "Product successfully Deleted"
        else
            flash[:error] = "Something went wrong"
        end
        redirect_to action: :manage_products
    end

    def edit
        @product = Product.find_by_id(params[:id])
        @categories = Category.all
    end

    def manage_products
        @products = Product.all
    end

    def search
        @products = Product.where("lower(name) like ?", "#{params[:search].downcase}%")
        @from = params[:from] 
        if @from.present?
            respond_to do |format|
                format.js { render :file => "products/sort.js.erb" }
            end
        end
    end

    def sort
        category = Category.find_by_id(params[:id])
        @products = category.products
    end

    private

    def product_params
        params.require(:product).permit(:id, :name,:price,:image,stock_attributes: [:count,:category_id])
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%=form_for(product) do |f|%>
    <%= flash_messages %>

    <div class="form-group row">
        <%= f.label :name ,class: "col-sm-2 col-form-label"%>
        <%= f.text_field :name, autofocus: true, class: "form-control col-sm-10",required: true %>
     </div>

     <div class="form-group row">
        <%= f.label :price ,class: "col-sm-2 col-form-label"%>
        <%= f.number_field :price, autofocus: true, class: "form-control col-sm-10", required: true %>
    </div>


    <%= f.fields_for :stock, product.stock || Stock.new do |ff| %>
        <div class="form-group row">
            <%= ff.label :category ,class: "col-sm-2 col-form-label"%>
            <%= ff.select :category_id, options_for_select(categories.map { |category| [category.name, category.id] }), {},{class:"form-control col-sm-10"} %>
         </div>
        <div class="form-group row">
            <%= ff.label :count ,class: "col-sm-2 col-form-label"%>
            <%= ff.number_field :count, autofocus: true, class: "form-control col-sm-10", required: true%>
         </div>
     <% end %>

    <div class="form-group row">
        <%= f.label :upload_image ,class: "col-sm-2 col-form-label"%>
        <%= f.file_field :image, autofocus: true, class: "form-control col-sm-10" %>
    </div>
      <%= f.submit "Create", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/products/_product.html.erb
<div class="col mb-6 product-card">
    <div class="card" style="width: 18rem;">
    <%= image_tag(product.image.url, class: "card-img-top card-size") %>
    <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text"><%= product.price %></p>
        <a href="#" class="btn btn-primary btn-block">Add to Cart</a>
    </div>
    </div>
</div>

app/views/products/_product_list.html.erb
<% if products.present? %>
    <table class="table table-hover table-lite">
    <thead>
        <tr>
        <th scope="col">Si No.</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% products.each_with_index do |product, i| %>
        <tr>
        <th scope="row"><%= i + 1 %></th>
        <td><%= product.name%></td>
        <td><%= product.price %></td>
        <td><%= link_to "Edit", edit_product_path(product)%></td>
        <td><%= link_to "Delete", product, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% else %>
    <div class="alert alert-dark" role="alert">
        No Products...
    </div>
 <% end %>

app/views/products/edit.html.erb
<%= render  "form", product: @product, categories: @categories %>

app/views/products/index.html.erb
<div class="">
    <%= text_field(:search, :search, size: 20, class: "form-control", placeholder: "Search...", id: "search")%>
</div>

<div class="row">
    <div class="col-2 ">
    <div class="list-group sticky-top" id="list-tab" role="tablist">
        <%= link_to  "All Categories", "#", class: "list-group-item list-group-item-action active"%>
        <% @categories.each do |category| %>
            <%= link_to  "#{category.name}", sort_path(id: category.id), class: "list-group-item list-group-item-action",onClick: "$(change_active(this));", remote: true %>
        <% end %>
    </div>

    </div>

    <div class="col">
        <div class="row row-cols-1 row-cols-md-3 product-index">
            <% @products.each do |product| %>
                <%= render  "product", product: product %>
            <% end %>
        </div>
    </div>
</div>

<script>
    function change_active(th_is) {
        $(".active").removeClass("active");
        $(th_is).addClass("active");
    }

    $("#search").keyup(function () {
        $.ajax({
        url: '/products/search',
        data: {
            search: $(this).val(),
            from: "index"
        }
        });
  });
    
</script>

app/views/products/manage_products.html.erb
<%= link_to "New Product", new_product_path, class: "btn btn-primary" %> 
<div class="">
    <%= text_field(:search, :search, size: 20, class: "form-control", placeholder: "Search...", id: "search")%>
</div>

<div class="product-list">
    <%= render  "product_list", products: @products %>
</div>
<script>
  //search on key press
  $("#search").keyup(function () {
    //   console.log($(this).val());
    // $(".todolist").empty();
    $.ajax({
      url: '/products/search',
      data: {
        search: $(this).val()
      }
    });
  });
</script>

app/views/products/new.html.erb
<%= render  "form", product: @product, categories: @categories %>

app/views/products/search.js.erb
$('.product-list').html(`
    <%= render 'product_list', products: @products %>
`);

app/views/products/sort.js.erb
$('.product-index').html(`
    <% @products.each do |product| %>
        <%= render  "product", product: product %>
    <% end %>
`);